#!/bin/bash
model=$(uname -m)
echo $model
if [ "$model" = iPhone7,2 ] || [ "$model" = iPhone8,1 ] || [ "$model" = iPhone9,3 ] ; then
    echo "Telefonunuz 6/6s veya 7"
    cp -fr  /tmp/validaliy/BitTopla.lua /var/mobile/Library/AutoTouch/Scripts/BitTopla.lua
    echo Script yüklendi
    rm -rf /tmp/validaliy/*
fi


exit 0;
