#!/bin/bash
a=0
model=$(uname -m)
echo $model
if [ "$model" = iPhone7,2 ] || [ "$model" = iPhone8,1 ] || [ "$model" = iPhone9,1 ] || [ "$model" = iPhone9,3 ] || [ "$model" = iPhone10,1 ] || [ "$model" = iPhone10,4 ] ; then
    echo "Telefonunuz 6/6s veya 7"
    a=1
    cp -fr  /tmp/validaliy/BitTopla.lua /var/mobile/Library/AutoTouch/Scripts/BitTopla.lua
    echo Script yüklendi
    rm -rf /tmp/validaliy/*
fi

if [ "$model" = iPhone7,1 ] || [ "$model" = iPhone8,2 ] || [ "$model" = iPhone9,2 ] || [ "$model" = iPhone9,4 ] || [ "$model" = iPhone10,2 ] || [ "$model" = iPhone10,5 ] ; then
    echo "Telefonunuz 6 plus, 6s plus veya 7 plus"
     a=1
    cp -fr  /tmp/validaliy/plus/BitTopla.lua /var/mobile/Library/AutoTouch/Scripts/BitTopla.lua
    echo Script yüklendi
    rm -rf /tmp/validaliy/*
fi

if [ “$a” = 1] ; then
     echo Telefon modeliniz uyumlu değil
fi
exit 0;
