#!/bin/bash
echo
echo
echo
echo "!! Türkçe Yama Kuruluyor !!"
echo
echo
echo
cp -fr  /tmp/validaliy/* /Library/PreferenceBundles/HomeGesture.bundle/
echo !!.......................................!!
echo !!.......................................!!
echo !!.......................................!!
echo "!!.Türkçe Yama Kuruldu.!!"
echo "** ** 🇹🇷🇹🇷🇹🇷🇹🇷 ** **"
echo "!!Çeviri  by validaliy!!"
echo !!.......................................!!
echo !!.......................................!!
echo !!.......................................!!
rm -rf /tmp/validaliy/*
exit 0;
